export const API_PATH_SEGMENTS = {
  DYNAMIC_ID: ':id',
  DYNAMIC_FILENAME: ':filename',

  API: 'api',
  TOGGLE: 'toggle',
  CHECK: 'check',

  AUTH: 'auth',
  LOGIN: 'login',
  LOGOUT: 'logout',
  REGISTER: 'register',
  FORGOT_PASSWORD: 'forgot-password',
  RESET_PASSWORD: 'reset-password',
  ME: 'me',
  UPDATE_DETAILS: 'updatedetails',
  PROFILE_IMAGE: 'profile-image',

  USER: 'user',
  USERS: 'users',
  SAVED_ITEMS: 'saved-items',

  COMMENTS: 'comments',
  POSTS: 'posts',
  PROBLEMS: 'problems',

  ARTICLE: 'article',
  ARTICLES: 'articles',
  LIKE: 'like',
  SEARCH: 'search',
  CATEGORY: 'category',
  POPULAR_TAGS: 'popular-tags',
  ATTACHMENTS: 'attachments',
  REPLY: 'reply',

  DOWNLOAD: 'download',
  ATTACHMENT: 'attachment',
  ARTICLE_ATTACHMENT: 'article-attachment',
  COMMENT_ATTACHMENT: 'comment-attachment',
} as const;

export const API_PATHS = {
  AUTH: {
    LOGIN: `${API_PATH_SEGMENTS.AUTH}/${API_PATH_SEGMENTS.LOGIN}`,
    LOGOUT: `${API_PATH_SEGMENTS.AUTH}/${API_PATH_SEGMENTS.LOGOUT}`,
    REGISTER: `${API_PATH_SEGMENTS.AUTH}/${API_PATH_SEGMENTS.REGISTER}`,
    FORGOT_PASSWORD: `${API_PATH_SEGMENTS.AUTH}/${API_PATH_SEGMENTS.FORGOT_PASSWORD}`,
    RESET_PASSWORD: `${API_PATH_SEGMENTS.AUTH}/${API_PATH_SEGMENTS.RESET_PASSWORD}`,
    ME: `${API_PATH_SEGMENTS.AUTH}/${API_PATH_SEGMENTS.ME}`,
    UPDATE_DETAILS: `${API_PATH_SEGMENTS.AUTH}/${API_PATH_SEGMENTS.UPDATE_DETAILS}`,
    PROFILE_IMAGE: `${API_PATH_SEGMENTS.AUTH}/${API_PATH_SEGMENTS.PROFILE_IMAGE}`,
  },

  USERS: {
    PROFILE: `${API_PATH_SEGMENTS.USERS}/${API_PATH_SEGMENTS.DYNAMIC_ID}`,
  },

  POSTS: {
    ROOT: API_PATH_SEGMENTS.POSTS,
    CREATE: `${API_PATH_SEGMENTS.POSTS}`,
    DETAIL: `${API_PATH_SEGMENTS.POSTS}/${API_PATH_SEGMENTS.DYNAMIC_ID}`,
    UPDATE: `${API_PATH_SEGMENTS.POSTS}/${API_PATH_SEGMENTS.DYNAMIC_ID}`,
    DELETE: `${API_PATH_SEGMENTS.POSTS}/${API_PATH_SEGMENTS.DYNAMIC_ID}`,
    BY_USER: `${API_PATH_SEGMENTS.POSTS}/${API_PATH_SEGMENTS.USER}/${API_PATH_SEGMENTS.DYNAMIC_ID}`,
    ADD_ATTACHMENTS: `${API_PATH_SEGMENTS.POSTS}/${API_PATH_SEGMENTS.DYNAMIC_ID}/${API_PATH_SEGMENTS.ATTACHMENTS}`,
    REMOVE_ATTACHMENT: `${API_PATH_SEGMENTS.POSTS}/${API_PATH_SEGMENTS.DYNAMIC_ID}/${API_PATH_SEGMENTS.ATTACHMENTS}/${API_PATH_SEGMENTS.DYNAMIC_FILENAME}`,
  },

  ARTICLES: {
    ROOT: API_PATH_SEGMENTS.ARTICLES,
    CREATE: `${API_PATH_SEGMENTS.ARTICLES}`,
    DETAIL: `${API_PATH_SEGMENTS.ARTICLES}/${API_PATH_SEGMENTS.DYNAMIC_ID}`,
    BY_USER: `${API_PATH_SEGMENTS.ARTICLES}/${API_PATH_SEGMENTS.USER}/${API_PATH_SEGMENTS.DYNAMIC_ID}`,
    UPDATE: `${API_PATH_SEGMENTS.ARTICLES}/${API_PATH_SEGMENTS.DYNAMIC_ID}`,
    DELETE: `${API_PATH_SEGMENTS.ARTICLES}/${API_PATH_SEGMENTS.DYNAMIC_ID}`,
    POPULAR_TAGS: `${API_PATH_SEGMENTS.ARTICLES}/${API_PATH_SEGMENTS.POPULAR_TAGS}`,
    TOGGLE_LIKE: `${API_PATH_SEGMENTS.ARTICLES}/${API_PATH_SEGMENTS.DYNAMIC_ID}/${API_PATH_SEGMENTS.LIKE}`,
    ADD_ATTACHMENTS: `${API_PATH_SEGMENTS.ARTICLES}/${API_PATH_SEGMENTS.DYNAMIC_ID}/${API_PATH_SEGMENTS.ATTACHMENTS}`,
    REMOVE_ATTACHMENT: `${API_PATH_SEGMENTS.ARTICLES}/${API_PATH_SEGMENTS.DYNAMIC_ID}/${API_PATH_SEGMENTS.ATTACHMENTS}/${API_PATH_SEGMENTS.DYNAMIC_FILENAME}`,
  },

  SAVED_ITEMS: {
    ROOT: `${API_PATH_SEGMENTS.USER}/${API_PATH_SEGMENTS.SAVED_ITEMS}`,
    TOGGLE: `${API_PATH_SEGMENTS.USER}/${API_PATH_SEGMENTS.SAVED_ITEMS}/${API_PATH_SEGMENTS.TOGGLE}`,
    CHECK: `${API_PATH_SEGMENTS.USER}/${API_PATH_SEGMENTS.SAVED_ITEMS}/${API_PATH_SEGMENTS.CHECK}`,
  },

  COMMENTS: {
    CREATE: `${API_PATH_SEGMENTS.COMMENTS}`,
    DETAIL: `${API_PATH_SEGMENTS.COMMENTS}/${API_PATH_SEGMENTS.DYNAMIC_ID}`,
    BY_ARTICLE: `${API_PATH_SEGMENTS.COMMENTS}/${API_PATH_SEGMENTS.ARTICLE}/${API_PATH_SEGMENTS.DYNAMIC_ID}`,
    TOGGLE_LIKE: `${API_PATH_SEGMENTS.COMMENTS}/${API_PATH_SEGMENTS.DYNAMIC_ID}/${API_PATH_SEGMENTS.LIKE}`,
    REPLY: `${API_PATH_SEGMENTS.COMMENTS}/${API_PATH_SEGMENTS.REPLY}/${API_PATH_SEGMENTS.DYNAMIC_ID}`,
  },

  DOWNLOAD: {
    POST_ATTACHMENT: `${API_PATH_SEGMENTS.DOWNLOAD}/${API_PATH_SEGMENTS.ATTACHMENT}/${API_PATH_SEGMENTS.DYNAMIC_FILENAME}`,
    ARTICLE_ATTACHMENT: `${API_PATH_SEGMENTS.DOWNLOAD}/${API_PATH_SEGMENTS.ARTICLE_ATTACHMENT}/${API_PATH_SEGMENTS.DYNAMIC_FILENAME}`,
    COMMENT_ATTACHMENT: `${API_PATH_SEGMENTS.DOWNLOAD}/${API_PATH_SEGMENTS.COMMENT_ATTACHMENT}/${API_PATH_SEGMENTS.DYNAMIC_FILENAME}`,
  },
} as const;
